name: naiyo24_business_tool
description: Naiyo24 Business Tool - Naiyo Business Tool-style Authentication Flow
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  http: ^1.2.0
  
  # Navigation
  go_router: ^14.2.0
  
  # UI
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.5.5
  intl: ^0.20.3
  
  uuid: any
  web: ^1.1.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/BusinessToolLogo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/BusinessToolLogo.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/images/BusinessToolLogo.png"
    icon_size: 256

flutter_native_splash:
  color: "#000000"
  image: assets/images/BTL.png
  android: true
  ios: true
  web: true
  image_dark: assets/images/BTL.png
  color_dark: "#000000"
  android_12:
    color: "#000000"
    image: assets/images/BTL.png
    color_dark: "#000000"
    image_dark: assets/images/BTL.png
  android_gravity: center
  ios_content_mode: scaleAspectFit
  web_image_mode: center
  fullscreen: true

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
