"""add_user_id_relations

Revision ID: 39af3556b061
Revises: 2a436622e129
Create Date: 2026-06-12 02:42:42.274954

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39af3556b061'
down_revision = '2a436622e129'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_invoices_users', 'users', ['user_id'], ['id'])
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_quotations_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quotations_users', type_='foreignkey')
        batch_op.drop_column('user_id')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invoices_users', type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
