"""align_items_invoices_and_expenses

Revision ID: 4b4e89b25a0c
Revises: b1b2c3d4e5f6
Create Date: 2026-07-08 11:20:54.065340

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '4b4e89b25a0c'
down_revision = 'b1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_account_groups_created_at'), 'account_groups', ['created_at'], unique=False)
    op.create_index(op.f('ix_accounts_created_at'), 'accounts', ['created_at'], unique=False)
    op.drop_index('ix_products_id', table_name='items')
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.add_column('purchase_orders', sa.Column('title', sa.String(length=150), nullable=True))
    op.add_column('purchase_orders', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('purchase_orders', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('vendors', sa.Column('contact_person', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'contact_person')
    op.drop_column('purchase_orders', 'total_amount')
    op.drop_column('purchase_orders', 'description')
    op.drop_column('purchase_orders', 'title')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.create_index('ix_products_id', 'items', ['id'], unique=False)
    op.drop_index(op.f('ix_accounts_created_at'), table_name='accounts')
    op.drop_index(op.f('ix_account_groups_created_at'), table_name='account_groups')
    # ### end Alembic commands ###
