"""update quotation fields

Revision ID: 88b8b6df932d
Revises: 68daa1577422
Create Date: 2026-07-07 23:58:49.119054

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '88b8b6df932d'
down_revision = '68daa1577422'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('customer_id', sa.String(length=50), nullable=True))
    op.add_column('quotations', sa.Column('customer_name', sa.String(length=150), nullable=False))
    op.add_column('quotations', sa.Column('customer_mobile', sa.String(length=20), nullable=True))
    op.add_column('quotations', sa.Column('customer_address', sa.String(length=300), nullable=True))
    op.add_column('quotations', sa.Column('customer_gst', sa.String(length=50), nullable=True))
    op.add_column('quotations', sa.Column('quotation_date', sa.Date(), nullable=True))
    op.add_column('quotations', sa.Column('valid_until', sa.Date(), nullable=True))
    op.add_column('quotations', sa.Column('payment_terms', sa.String(length=150), nullable=True))
    op.add_column('quotations', sa.Column('currency', sa.String(length=20), nullable=True))
    op.drop_column('quotations', 'client_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('client_name', sa.VARCHAR(length=150), nullable=False))
    op.drop_column('quotations', 'currency')
    op.drop_column('quotations', 'payment_terms')
    op.drop_column('quotations', 'valid_until')
    op.drop_column('quotations', 'quotation_date')
    op.drop_column('quotations', 'customer_gst')
    op.drop_column('quotations', 'customer_address')
    op.drop_column('quotations', 'customer_mobile')
    op.drop_column('quotations', 'customer_name')
    op.drop_column('quotations', 'customer_id')
    # ### end Alembic commands ###
